# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://gruss.dev
title: Ryan Gruss - Software Developer in Seattle WA
email: ryan@gruss.dev
author: Ryan Gruss
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 Ryan Gruss. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: resume
    url: /files/resume.pdf
    icon: far fa-file-pdf
  - title: github
    url: https://github.com/grussr
    icon: fab fa-github
  - title: linkedin
    url: https://www.linkedin.com/ryangruss
    icon: fab fa-linkedin
